### ISSUE TITLE
Permission to attempt to merge this fork upstream

### ISSUE THREAD

**Issue by landfillbaby** [landfillbaby/pngcheck-oldfork#1]
@jbowler @lemniscati
The upstream seems to be active again as of the 2.4.0 release at the end of October.
I'm considering sending the contents of this fork as a series of patches to the png-mng-implement mailing list for approval.
Of course, without permission from both of you, I can only submit my own sole contribution of adding a single character.
Do you think this would be a good idea?
Of course you can also feel free to submit these patches yourselves instead of saying I can do it.

Edit: I just realized almost immediately after posting this that due to the open license I technically could do this without your approval, but I still would rather not do so.

**Comment by lemniscati** [comment]
Thank you. @landfillbaby . 
About my part, please do it.

**Comment by landfillbaby** [comment]
https://sourceforge.net/p/png-mng/mailman/png-mng-implement/?viewmonth=202012
by the way here's the link to the messages i've sent

**Comment by jbowler** [comment]
So I deleted it; I did so because you may not and, as I think I proved, you
cannot use me as a conduit to push changes back upstream.  I suggest you
find a maintainer.

John Bowler <jbowler@acm.org>
+1 (541) 450-9885
PO BOX 3151
KERBY OR 97531-3151
USA

**Comment by landfillbaby** [comment]
ok then. sorry
